// <auto-generated />
namespace BokkingRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class BusTicketBookingDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BusTicketBookingDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202003100647408_BusTicketBookingDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
